#!/bin/sh

# Feed script a url or file location.
# If an image, it will view in $imggram,
# if a video or gif, it will view in mpv
# if a music file or pdf, it will download,
# otherwise it opens link in browser.

if [ -n $WAYLAND_DISPLAY ]; then
  url="$(wl-paste)"
  imggram=imv
  browser=firefox-wl
else
  url="$(xclip -o)"
  imggram=feh
  browser=firefox
fi

if [ -n "$1" ]; then
  url="$1"
fi

browser_args="about:reader?url=$url"
if [ -n "$2" ]; then
  if [ "$2" == "noread" ]; then
    browser_args="$url"
  fi
fi

case "$url" in
	*mkv|*webm|*mp4|*youtube.com/watch*|*youtube.com/playlist*|*youtube.com/shorts*|*youtu.be*|*hooktube.com*|*bitchute.com*|*videos.lukesmith.xyz*|*odysee.com*|*video/enc*)
		setsid -f mpv -quiet "$url" >/dev/null 2>&1 ;;
	*webp|*png|*jpg|*jpe|*jpeg|*gif)
		curl -sL "$url" > "/tmp/$(echo "$url" | sed "s/.*\///;s/%20/ /g")" && $imggram "/tmp/$(echo "$url" | sed "s/.*\///;s/%20/ /g")"  >/dev/null 2>&1 & ;;
	*pdf|*cbz|*cbr)
		curl -sL "$url" > "/tmp/$(echo "$url" | sed "s/.*\///;s/%20/ /g")" && zathura "/tmp/$(echo "$url" | sed "s/.*\///;s/%20/ /g")"  >/dev/null 2>&1 & ;;
	*mp3|*flac|*opus|*mp3?source*)
		qndl "$url" 'curl -LO'  >/dev/null 2>&1 ;;
	*)
		[ -f "$url" ] && setsid -f "$TERMINAL" -e "$EDITOR" "$url" >/dev/null 2>&1 || setsid -f "$browser" "$browser_args" >/dev/null 2>&1
esac
