#!/bin/bash

exec swaylock -f \
	--screenshots \
	--clock \
	--indicator \
    --text-color ffffff \
	--indicator-radius 100 \
	--indicator-thickness 7 \
	--effect-blur 7x5 \
	--effect-vignette 0.5:0.5 \
	--ring-color 00000000 \
	--key-hl-color 2ac3de \
	--line-color 2ac3de \
	--inside-color 00000000 \
    --separator-color 00000000 \
	--grace 2 \
	--fade-in 0.2
