#!/bin/bash

check_process_killall() {
    [ "$1" = "" ]  && return 0
    [ `pgrep -n $1` ] && killall $1 || return 0
}

check_process_pkill() {
    [ "$1" = "" ]  && return 0
    [ `pgrep -n $1` ] && killall $1 || return 0
}

check_process_killall dwmblocks
check_process_pkill redshift
check_process_pkill dunst
check_process_killall mpd_discord_richpresence

exec picom --experimental-backends &
exec nitrogen --restore &
exec dunst &
exec mappings &
exec dwmblocks &
exec redshift -l $(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" | jq -r '"\(.location.lat):\(.location.lng)"') &
exec mpd_discord_richpresence &
