#!/bin/bash

xrandr --output HDMI-A-0 --mode 1920x1200 --rate 75
xrandr --output DisplayPort-0 --mode 3440x1440 --rate 144

check_process_killall() {
    [ "$1" = "" ]  && return 0
    [ `pgrep -n $1` ] && killall $1 || return 0
}

check_process_pkill() {
    [ "$1" = "" ]  && return 0
    [ `pgrep -n $1` ] && killall $1 || return 0
}

check_process_killall dwmblocks
check_process_pkill redshift
check_process_pkill dunst
check_process_killall mpd-discord-rpc
check_process_killall easyeffects
check_process_killall fcitx5

exec picom &
exec nitrogen --restore &
exec dunst &
exec mappings &
exec dwmblocks &
exec redshift -l $(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" | jq -r '"\(.location.lat):\(.location.lng)"') -b 0.85:1.00 &
exec mpd-discord-rpc &
exec fcitx5 -d &
